### ISSUE TITLE
PIX - Atualização do Pedido no painel do WP WooCommerce

### ISSUE THREAD

**Issue by xxGus** [iugu/iugu-new-woocommerce#2]
Após concluir a compra via PIX, o pedido gerado no painel WP WooCommerce não atualiza o status para "Concluído"

**Comment by labfantasma** [comment]
Qual status o pedido fica no seu painel após a confirmação da Iugu @xxGus ? **Aguardando** ou ele vai para **Processando**?

**Comment by xxGus** [comment]
Ele ficava em "Aguardando" mas isso foi resolvido, descobrimos que um outro plugin estava impedindo essa mudança de status. Depois de desinstalar, passou a atualizar.

**Comment by jpdroid** [comment]
> ssou

qual plugin?
